In [76]:
# description of this dataset http://groupware.les.inf.puc-rio.br/har#ixzz2PyRdbAfA
from sklearn import datasets
from sklearn import preprocessing as pp
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
import numpy
import csv
import pandas as pd
import time

initial = time.time()
### Retrieving all data
data = pd.read_csv("./adriel.csv", delimiter=';', header=None)


In [77]:
data.shape

(36030, 18)

In [78]:
X = pp.normalize(data)

In [79]:
def segment_signal(data, window_size): 

    N = data.shape[0]
    dim = data.shape[1]
    K = N/window_size
    segments = numpy.empty((K, window_size, dim))
    for i in range(K):
        segment = data[i*window_size:i*window_size+window_size,:]
        segments[i] = numpy.vstack(segment)
    return segments

In [80]:
window_size = 12

segs = segment_signal(X, window_size) # 40 * 50ms = 2000ms
segs.shape

(3002, 12, 18)

In [81]:
def extract_diff_2(raw):

    N = raw.shape[0] # number of segments of sensor readings ()
    I = raw.shape[1] # number of sets of readings (14)
    J = raw.shape[2] # number of values in each set of readings (12)
    feature_num = (I - 1) * J
    feature = numpy.empty((feature_num))
    features = numpy.empty((N, feature_num))
    for n in range(N):
        idx = 0;
        for i in range(1, I):
            for j in range(J):
                feature[idx] = raw[n][i][j] - raw[n][i-1][j]
                idx += 1
        features[n] = feature
        

    return features

In [82]:
features = extract_diff_2(segs)

In [83]:
features.shape

(3002, 198)

In [84]:
le = pp.LabelEncoder() 
le.fit(['wavehands', 'busdriver', 'frontback', 'sidestep',  # currently 8 actions
        'turnclap', 'squatturnclap', 'window', 'window360'])

LabelEncoder()

In [48]:
# Creating label 
targetNum = data.shape[0] / window_size

y = numpy.empty(targetNum)

index = 0
for k in range(8):
    for j in range(targetNum/8):
        y[index] = k
        index += 1
        
y.shape

(800,)

In [117]:
def generate_label(overall_size, class_size, segment_size):
    y = numpy.empty(overall_size/segment_size)
    index = 0
    for k in range(class_size):
        for j in range((overall_size/class_size)/segment_size):
            y[index] = k
            index += 1
    return y

In [132]:
ts1 = generate_label(overall_size=9608, class_size=8, segment_size=12) #training set 1: 
print ts1.shape
ts2 = generate_label(overall_size=9608, class_size=8, segment_size=12) #training set 2: 
print ts2.shape
ts3 = generate_label(overall_size=8407, class_size=7, segment_size=12) #training set 3: 
print ts3.shape
ts4 = generate_label(overall_size=8407, class_size=7, segment_size=12) #training set 4: 
print ts4.shape

(800,)
(800,)
(700,)
(700,)


In [143]:
temp1 = numpy.append(ts1, ts2)
temp2 = numpy.append(ts3, ts4)
y = numpy.append(temp1, temp2)
y.shape

(3000,)

In [144]:
add1 = numpy.array([1])
y = numpy.append(y, add1)
y = numpy.append(y, add1)
y.shape

(3002,)

In [145]:
layer_1_val = 15
layer_2_val = 10
################################################################
####having 15 neurons
kfold = KFold(n_splits=10, shuffle=True)
fold_index = 0
for train, test in kfold.split(features):
    clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                     hidden_layer_sizes=(layer_1_val, layer_2_val), random_state=1).fit(features[train], y[train])
    predictions = clf.predict(features[test])
    accuracy = clf.score(features[test], y[test])
    cm = confusion_matrix(y[test], predictions)

    print('In the %i fold, the classification accuracy is %f' %(fold_index, accuracy))
    print('And the confusion matrix is: ')
    print(cm)
    fold_index += 1
#############################################################
##### Choose by uncommenting on either one
#############################################################
# kfold = KFold(n_splits=10, shuffle=True)

# fold_index = 0
# for train, test in kfold.split(features):
#     svm = SVC(kernel = 'linear', C = 50).fit(features[train], y[train])
#     svm_predictions = svm.predict(features[test])
#     recall = recall_score(y[test], svm_predictions, average='macro') # 
#     accuracy = svm.score(features[test], y[test])
#     cm = confusion_matrix(y[test], svm_predictions)

#     print('In the %i fold, the classification accuracy is %f and the recall is %f' %(fold_index, accuracy, recall))
#     print('And the confusion matrix is: ')
#     print(cm)
#     fold_index += 1
################################################################

In the 0 fold, the classification accuracy is 0.744186
And the confusion matrix is: 
[[34  1  1  0  1  1  0  0]
 [ 3 33  2  0  1  0  0  0]
 [ 0  2 23  7 12  1  0  0]
 [ 0  0  4 31  0  1  0  0]
 [ 0  1  2  2 27  9  0  0]
 [ 1  1  0  1 16 17  0  0]
 [ 0  0  0  0  0  1 46  1]
 [ 0  0  0  0  0  0  5 13]]
In the 1 fold, the classification accuracy is 0.651163
And the confusion matrix is: 
[[30  2  0  0  0  0  0  0]
 [ 1 33  0  1  0  0  0  0]
 [ 0  1 20 19  3  9  0  0]
 [ 0  1  9 26  1  2  0  0]
 [ 0  0  3  2 14 17  0  0]
 [ 0  0  6  1 15 25  0  0]
 [ 1  0  0  1  1  0 32  3]
 [ 0  0  0  0  2  0  4 16]]
In the 2 fold, the classification accuracy is 0.723333
And the confusion matrix is: 
[[42  2  1  0  0  0  0  0]
 [ 1 42  0  0  0  0  0  0]
 [ 0  1 18  9  3  2  0  0]
 [ 0  0  9 32  1  3  0  0]
 [ 0  1  1  1 16 17  0  0]
 [ 0  0  6  0 15 20  0  1]
 [ 2  0  0  0  0  0 27  2]
 [ 1  0  0  0  0  0  4 20]]
In the 3 fold, the classification accuracy is 0.676667
And the confusion matrix is: 
[[39  2  

In [15]:
data

0        1        2        3        4        5        6        7   \
0      6812.0  -3396.0  -7148.0   4962.0   4813.0 -20029.0   3972.0   5640.0   
1      5904.0    540.0  -3728.0  13788.0   1977.0 -21460.0   2832.0   2320.0   
2      7760.0   7284.0  -3028.0   7359.0  -5367.0 -20499.0   4088.0  -4952.0   
3     11572.0  10316.0  -2072.0   7043.0  -4187.0 -18170.0   1328.0  -9364.0   
4     13132.0  11772.0  -6128.0   6702.0 -14349.0 -12547.0   7088.0 -19652.0   
5     22792.0  13648.0 -11584.0   8512.0 -15276.0  -6565.0  13456.0 -29732.0   
6     29100.0  15404.0 -18512.0   6401.0  -9049.0  -1986.0  24084.0 -32768.0   
7     26800.0  18108.0 -20504.0   2073.0   5540.0   6006.0  21632.0 -32268.0   
8     18360.0  15132.0 -13308.0  -1426.0  14496.0  15019.0  12640.0 -24396.0   
9     10008.0  11172.0  -9080.0  -3244.0  16027.0  18943.0   4332.0 -16140.0   
10     4384.0   6296.0  -5244.0  -8613.0  11960.0  20797.0  -1852.0  -7320.0   
11     2876.0  -1012.0  -3880.0 -10420.0   5386.0  22610.0  -3180.0   -416.0   
12     4672.0  -7080.0  -4876.0  -8468.0   -868.0  21005.0   1496.0   9236.0   
13     7324.0 -19744.0 -10964.0  -1834.0  -3256.0  13892.0   7992.0  18288.0   
14     7620.0 -19940.0 -13164.0  -3304.0   4486.0   -841.0   8736.0  18152.0   
15     8164.0 -17452.0  -9824.0  -8676.0   7756.0 -11738.0   7364.0  15436.0   
16     6624.0 -10096.0  -5204.0  -1296.0   7281.0 -15521.0   3660.0   8588.0   
17     6316.0  -4336.0  -2708.0   3195.0   2848.0 -18078.0   2120.0   2644.0   
18     6180.0   -944.0  -1648.0   8570.0  -2774.0 -17867.0   2952.0  -1028.0   
19     7452.0   4380.0  -3416.0  10047.0 -10230.0 -18002.0   2680.0  -6332.0   
20     9676.0  10260.0  -6608.0  12888.0 -14663.0 -15620.0   2596.0 -15076.0   
21    17372.0  15720.0 -14868.0   5124.0 -22085.0 -10507.0  10768.0 -22632.0   
22    25700.0  15588.0 -20464.0   8945.0 -12956.0  -1445.0  23764.0 -32768.0   
23    27732.0  16496.0 -20632.0   1575.0   1341.0   3507.0  27364.0 -29324.0   
24    20776.0  13800.0 -17248.0  -1021.0  11900.0   8281.0  18484.0 -27504.0   
25    14176.0  10396.0 -11436.0  -3655.0  15108.0  13710.0  10672.0 -19028.0   
26     8900.0   6960.0  -7900.0  -3314.0  14029.0  16468.0   3628.0 -11224.0   
27     5936.0   4060.0  -4840.0  -6062.0  11152.0  17787.0    396.0  -6220.0   
28     3836.0   -144.0  -3460.0  -7815.0   5385.0  18512.0  -1208.0    848.0   
29     4348.0  -3636.0  -2944.0  -9112.0  -1154.0  17731.0   1316.0   4504.0   
...       ...      ...      ...      ...      ...      ...      ...      ...   
9578   5280.0   8916.0 -27792.0  -1458.0 -11443.0  29071.0  13128.0  -7004.0   
9579   1740.0   8376.0 -31660.0   -365.0   -621.0  30520.0   7732.0  -5904.0   
9580  -1692.0    468.0 -31848.0  -3501.0   8516.0  28310.0   5788.0    500.0   
9581  -2512.0  -2964.0 -28144.0    376.0  15138.0  21272.0   2876.0   1052.0   
9582  -2400.0  -5836.0 -21980.0  -1858.0  17993.0  14286.0   1064.0   1496.0   
9583  -1280.0  -7056.0 -16136.0   -430.0  15965.0   6509.0    436.0    224.0   
9584   -152.0  -4872.0 -11532.0  -3007.0  12328.0   1410.0   -356.0  -2696.0   
9585   1040.0  -2088.0  -6880.0  -5126.0   8449.0  -1985.0  -1260.0  -3492.0   
9586   1404.0  -1248.0  -4072.0  -2330.0   3650.0  -4516.0  -2060.0  -5424.0   
9587   2784.0   1808.0  -2764.0   2088.0  -2054.0  -6558.0  -2096.0  -7700.0   
9588   3344.0   6108.0  -2808.0    253.0  -9117.0  -7856.0   -216.0 -10540.0   
9589   2736.0   9972.0  -6352.0    -87.0 -18606.0  -6370.0    620.0 -13516.0   
9590   5132.0  15444.0 -11480.0   1195.0 -26167.0   -659.0   4944.0 -17280.0   
9591   5636.0  19224.0 -17068.0   1656.0 -29251.0   7937.0   8704.0 -20588.0   
9592   4396.0  17236.0 -25032.0  -1541.0 -26267.0  22106.0  13952.0 -17480.0   
9593   2440.0  11828.0 -29988.0   4474.0 -14871.0  31870.0  15620.0  -9500.0   
9594    512.0   9512.0 -29888.0   1782.0  -2226.0  32767.0  14168.0  -2108.0   
9595   -120.0   2216.0 -30216.0   3550.0   8472.0  31004.0   8808.0   1360.0   
9596  -2752